### ISSUE TITLE
issues on: seo tools, media manager, ckeditor, js links

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#11] opened 2012-01-04 16:58 UTC
I've made a new fresh install (at 12:00 am more or less). I've downloaded all modules from github using the zip links.
I've found these problems:
1. on installing and activating seo tools module I have no problems, i can edit settings too but I receive an error page with this message when I click on the menu "Seo Tools" in the back office top bar (/admin/seo_tools/urls):
   "Missing Database Table
   Error: Table qa_seo_tools_urls for model SeoUrl was not found in datasource default.
   Notice: If you want to customize this error message, create /home/gabri/workspace/quickapps/View/Errors/missing_table.ctp"
   Note: But after reinstalling it (and tried other things) now I have "just" a 500 internal server error on url: admin/seo_tools/urls
2. a problem on media manager, I see an error (url path I presume) on loading this js: mediamanager/js/elfinder/i18n/elfinder.en.js
   When I try to add a new directory I have an error message that disappear almost immediately on confirming the name "invalid backend configuration" and no folder is created (it seems not a problem of permissions on filesystem).
   But I had no problems uploading images (both in "slider" than "uploads" dir)
3. in backoffice login page url to js are not valid: /js/jquery.js and not (like frontend) /system/js/jquery.js (the same for quickapps.js)
4. I believe there is a problem on js urls on something regarding ckeditor too
   When I try to add a new image clicking on the image button, then i click on "find on server" (more or less), this open a new browser page with "finder" as output but a lot of js errors (files not found)
   I can see this js error on loading a page (in backend) with ckeditor enabled (but maybe it's not a big problem):
   uncaught exception: [CKEDITOR.editor] The instance "FieldDataFieldText3Data" already exists.

Thanks for your work

**Comment by quickapps** [comment] 2012-01-04 20:46
Well, I think I have fixed all the issues, 
1. This was caused by an incorrect table creation on install process. (Due to the new cake 2.1 version I believe).
2. I have added a php code that does not include the language .js if it does not exists.
   Also, the folder creation issues was caused by pressing `Intro` key after write the folder name. (fixed)
3. 1aa01c9675b2ad86a133541d30fb577f8c171bd6  more issues :S
4. This was caused by an incorrect path to jquery lib....yes, 1aa01c9675b2ad86a133541d30fb577f8c171bd6 again =)

Checks that everything works fine to close this ticket.

Thanks!

**Comment by Gabri** [comment] 2012-01-04 22:25
Everything work fine except the point one.
With a fresh new install and the new module Seo Tool I had the same result the first time I clicked on the link in the top bar:
Missing Database Table
Error: Table qa_seo_tools_urls for model SeoUrl was not found in datasource default.
Notice: If you want to customize this error message, create /home/gabri/workspace/quickapps/View/Errors/missing_table.ctp
Stack Trace
APP/Cake/Model/Model.php line 3334 → Model->setSource(string)
APP/Cake/Model/Model.php line 1277 → Model->getDataSource()
APP/Cake/Model/Model.php line 1363 → Model->schema()
APP/Model/Behavior/WhoDidItBehavior.php line 49 → Model->hasField(string)
APP/Cake/Model/BehaviorCollection.php line 145 → WhoDidItBehavior->setup(SeoUrl, array)
APP/Cake/Model/BehaviorCollection.php line 68 → BehaviorCollection->load(string, array)
APP/Cake/Model/Model.php line 723 → BehaviorCollection->init(string, array)
APP/Model/AppModel.php line 23 → Model->__construct(array, null, null)
[internal function] → AppModel->__construct(array)
APP/Cake/Utility/ClassRegistry.php line 161 → ReflectionClass->newInstance(array)
APP/Cake/Controller/Controller.php line 710 → ClassRegistry::init(array)
APP/Cake/Controller/Controller.php line 367 → Controller->loadModel(string)
APP/Cake/Controller/Component/PaginatorComponent.php line 237 → Controller->__isset(string)
APP/Cake/Controller/Component/PaginatorComponent.php line 117 → PaginatorComponent->_getObject(string)
APP/Cake/Controller/Controller.php line 1058 → PaginatorComponent->paginate(string, array, array)
CORE/quickapps/Modules/SeoTools/Controller/UrlsController.php line 26 → Controller->paginate(string)
[internal function] → UrlsController->admin_index()
APP/Cake/Controller/Controller.php line 484 → ReflectionMethod->invokeArgs(UrlsController, array)
APP/Cake/Routing/Dispatcher.php line 104 → Controller->invokeAction(CakeRequest)
APP/Cake/Routing/Dispatcher.php line 86 → Dispatcher->_invoke(UrlsController, CakeRequest, CakeResponse)
CORE/quickapps/webroot/index.php line 47 → Dispatcher->dispatch(CakeRequest, CakeResponse)

Then I tried to uninistall it and i had this error (admin/system/modules/uninstall/SeoTools):
Notice (8): Undefined variable: Installer [CORE/quickapps/Modules/SeoTools/Controller/Component/InstallComponent.php, line 39]
Notice (8): Trying to get property of non-object [CORE/quickapps/Modules/SeoTools/Controller/Component/InstallComponent.php, line 39]
Notice (8): Trying to get property of non-object [CORE/quickapps/Modules/SeoTools/Controller/Component/InstallComponent.php, line 39] Fatal error: Call to a member function getDataSource()...

The second time trying to uninstall I had this message:
Module does not exists.

After that I delete manually all files on Modules/SeoTools and i put on it the files from the zip ...and strangely now seems to work  :)

**Comment by quickapps** [comment] 2012-01-04 22:37
Hmm, for some reason it fails when debug = 0, I think it is a problem related to cake's cache files.
If you manually delete all the models cache (tmp/cache/models) it get solved.
I'll keep looking.

**Closed as completed** 2012-01-04 23:34 UTC
Labels: Resolved
