### ISSUE TITLE
Problem on traslate contents

### ISSUE THREAD

**Issue by Gabri** [quickapps/cms#51] opened 2012-04-22 21:00 UTC
Hi Chris,

There is a problem clicking on the "translate" link of a content that has set a specific language.
It seems that the find filter condition is not correct on ContentsController > admin_translate (line 109):
- my content (i don't know why) has not a 'NULL' value on "translation_of" field (it's just empty)
- it looks for a node that has "___" in the "language" field ...but that node has the language that I choose (ita)

**Comment by quickapps** [comment] 2012-04-22 21:18
```
 'Node.language LIKE' => '___',
```

http://dev.mysql.com/doc/refman/5.1/en/pattern-matching.html
"...SQL pattern matching enables you to use “_” to match any single character and “%” to match an arbitrary number of..."

---

Are you experiencing some unexpected behavior ?

Because my local installation seems to work properly.
Maybe the not 'NULL' value on `translation_of` may produce some problems, in that case try replacing this line:

```
 'Node.translation_of' => null
```

for this other:

```
 'Node.translation_of' => array(null, '')
```

**Comment by Gabri** [comment] 2012-04-22 21:48
Wow, I didn't know about the "_" char in MySql!  :)

I understood why my content has the translation field empty and not 'NULL'. It was, in past, a sample content inserted during the installation, and those contents have that field set with emtpy string (better to adjust).

adding:
<code>'Node.translation_of' => array(null, '')</code>
now I have a step forward (previous clicking on 'translate' doesn't do anything): the page "Translating Content" where there is the title and the 'Translate to' select list, but when I click on the 'Translate'/submit button it remains in that page without messages and not in the page to insert the translated content

Thanks

**Comment by Gabri** [comment] 2012-04-22 22:14
But with a new content (and the "translation_of" field == NULL) the problem is the same as in the beginning: no page "Translating Content" open. The result of the query is 'false' with:
<code>'Node.translation_of' => array(null, '')</code>

**Comment by quickapps** [comment] 2012-04-23 11:39
https://github.com/QuickAppsCMS/QuickApps-CMS/commit/ad41bee39f30014ffc5d15a2dbbd76b2a3986f60

I think this may solve the issue, confirm to close this ticket.

Regards

**Closed as completed** 2012-04-23 19:09 UTC
Labels: Resolved
