### ISSUE TITLE
Timezone not set

### ISSUE THREAD

**Issue by rabol** [quickapps/cms#4] opened 2011-11-07 10:33 UTC
Timezone should be set before using any time related functions otherwise your /tmp/logs/error.log will be full of warnings (and slow down the system)

**Comment by quickapps** [comment] 2011-11-07 11:28
This is actually set on controller "bootstrap", this is before controller's `beforeFilter()`.
In Quickapps component, on `initialize()`; after load enviroment variables and user access checking process.
So it is actually set before using any time related function.

Are you getting timezone-related warnings?
This may be caused by other reason, because demo site and other tests installations doesnt show any time-related warning in `error.log`

**Comment by rabol** [comment] 2011-11-07 11:33
yes I get time zone warnings:
2011-11-07 10:45:13 Warning: Warning (2): strtotime(): It is not safe to rely on the system's timezone settings. You are _required_ to use the date.timezone setting or the date_default_timezone_set() function. In case you used any of those methods and you are still getting this warning, you most likely misspelled the timezone identifier. We selected 'Europe/Berlin' for 'CET/1.0/no DST' instead in [/Web/quickapps/QuickApps-CMS/app/Cake/Network/CakeResponse.php, line 631]
Trace:
strtotime - [internal], line ??
CakeResponse::cache() - APP/Cake/Network/CakeResponse.php, line 631
Dispatcher::_deliverAsset() - APP/Cake/Routing/Dispatcher.php, line 321
Dispatcher::asset() - APP/Cake/Routing/Dispatcher.php, line 293
Dispatcher::dispatch() - APP/Cake/Routing/Dispatcher.php, line 74
[main] - APP/webroot/index.php, line 81

I fixed it by adding a few lines to my .htaccess

System:
Darwin Steens-iMac 11.2.0 Darwin Kernel Version 11.2.0: Tue Aug 9 20:54:00 PDT 2011; root:xnu-1699.24.8~1/RELEASE_X86_64 x86_64
Apache/2.2.20 (Unix) DAV/2 PHP/5.3.6 with Suhosin-Patch
PHP v. 5.3.6

**Comment by quickapps** [comment] 2011-11-07 12:00
Interesting,
But this warining is showing up on Dispatch process, this is just before load bootstrap.php.
So teorically you should get this warning in any cakePHP application.

Check the `date.timezone` ini option in your php.ini file. And make sure you have a value set on it.

(cakePHP use time functions on Dispatch process for setting up header info and creating Cache Files)

http://hints.macworld.com/article.php?story=20090831101932728

Notify me when you fix it to close this ticket :)

**Closed as completed** 2011-11-13 13:43 UTC
Labels: Invalid
